// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tes_array.proto

#include "tes_array.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mathtest {
PROTOBUF_CONSTEXPR MathRequest::MathRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_)*/0
  , /*decltype(_impl_.b_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MathRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MathRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MathRequestDefaultTypeInternal() {}
  union {
    MathRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MathRequestDefaultTypeInternal _MathRequest_default_instance_;
PROTOBUF_CONSTEXPR MathReply::MathReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MathReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MathReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MathReplyDefaultTypeInternal() {}
  union {
    MathReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MathReplyDefaultTypeInternal _MathReply_default_instance_;
PROTOBUF_CONSTEXPR Mathhasil::Mathhasil(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_float_)*/{}
  , /*decltype(_impl_.header_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MathhasilDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MathhasilDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MathhasilDefaultTypeInternal() {}
  union {
    Mathhasil _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MathhasilDefaultTypeInternal _Mathhasil_default_instance_;
PROTOBUF_CONSTEXPR RecBro::RecBro(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.header_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.totalpaket_)*/0
  , /*decltype(_impl_.paket_ke_)*/0
  , /*decltype(_impl_.mintatipe_)*/0
  , /*decltype(_impl_.mintaparam_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RecBroDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RecBroDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RecBroDefaultTypeInternal() {}
  union {
    RecBro _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RecBroDefaultTypeInternal _RecBro_default_instance_;
PROTOBUF_CONSTEXPR Datablob::Datablob(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.header_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dataku_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.totalpaket_)*/0
  , /*decltype(_impl_.paket_ke_)*/0
  , /*decltype(_impl_.tipe_data_)*/0
  , /*decltype(_impl_.param_)*/0
  , /*decltype(_impl_.timeepoch_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DatablobDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DatablobDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DatablobDefaultTypeInternal() {}
  union {
    Datablob _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DatablobDefaultTypeInternal _Datablob_default_instance_;
}  // namespace mathtest
static ::_pb::Metadata file_level_metadata_tes_5farray_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_tes_5farray_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_tes_5farray_2eproto = nullptr;

const uint32_t TableStruct_tes_5farray_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mathtest::MathRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mathtest::MathRequest, _impl_.a_),
  PROTOBUF_FIELD_OFFSET(::mathtest::MathRequest, _impl_.b_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mathtest::MathReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mathtest::MathReply, _impl_.result_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mathtest::Mathhasil, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mathtest::Mathhasil, _impl_.header_),
  PROTOBUF_FIELD_OFFSET(::mathtest::Mathhasil, _impl_.result_float_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mathtest::RecBro, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mathtest::RecBro, _impl_.header_),
  PROTOBUF_FIELD_OFFSET(::mathtest::RecBro, _impl_.totalpaket_),
  PROTOBUF_FIELD_OFFSET(::mathtest::RecBro, _impl_.paket_ke_),
  PROTOBUF_FIELD_OFFSET(::mathtest::RecBro, _impl_.mintatipe_),
  PROTOBUF_FIELD_OFFSET(::mathtest::RecBro, _impl_.mintaparam_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mathtest::Datablob, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mathtest::Datablob, _impl_.header_),
  PROTOBUF_FIELD_OFFSET(::mathtest::Datablob, _impl_.totalpaket_),
  PROTOBUF_FIELD_OFFSET(::mathtest::Datablob, _impl_.paket_ke_),
  PROTOBUF_FIELD_OFFSET(::mathtest::Datablob, _impl_.tipe_data_),
  PROTOBUF_FIELD_OFFSET(::mathtest::Datablob, _impl_.param_),
  PROTOBUF_FIELD_OFFSET(::mathtest::Datablob, _impl_.timeepoch_),
  PROTOBUF_FIELD_OFFSET(::mathtest::Datablob, _impl_.dataku_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mathtest::MathRequest)},
  { 8, -1, -1, sizeof(::mathtest::MathReply)},
  { 15, -1, -1, sizeof(::mathtest::Mathhasil)},
  { 23, -1, -1, sizeof(::mathtest::RecBro)},
  { 34, -1, -1, sizeof(::mathtest::Datablob)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mathtest::_MathRequest_default_instance_._instance,
  &::mathtest::_MathReply_default_instance_._instance,
  &::mathtest::_Mathhasil_default_instance_._instance,
  &::mathtest::_RecBro_default_instance_._instance,
  &::mathtest::_Datablob_default_instance_._instance,
};

const char descriptor_table_protodef_tes_5farray_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017tes_array.proto\022\010mathtest\"#\n\013MathReque"
  "st\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(\005\"\033\n\tMathReply\022\016\n"
  "\006result\030\001 \001(\005\"1\n\tMathhasil\022\016\n\006header\030\001 \001"
  "(\t\022\024\n\014result_float\030\002 \003(\002\"e\n\006RecBro\022\016\n\006he"
  "ader\030\001 \001(\t\022\022\n\ntotalpaket\030\002 \001(\005\022\020\n\010paket_"
  "ke\030\003 \001(\005\022\021\n\tMintaTipe\030\004 \001(\005\022\022\n\nMintaPara"
  "m\030\005 \001(\005\"\205\001\n\010Datablob\022\016\n\006header\030\001 \001(\t\022\022\n\n"
  "totalpaket\030\002 \001(\005\022\020\n\010paket_ke\030\003 \001(\005\022\021\n\tti"
  "pe_data\030\004 \001(\005\022\r\n\005param\030\005 \001(\005\022\021\n\ttimeEpoc"
  "h\030\006 \001(\005\022\016\n\006dataku\030\007 \001(\0142\270\001\n\010MathTest\022;\n\013"
  "SendRequest\022\025.mathtest.MathRequest\032\023.mat"
  "htest.MathReply\"\000\0229\n\tSendarray\022\025.mathtes"
  "t.MathRequest\032\023.mathtest.Mathhasil\"\000\0224\n\n"
  "Softhaliza\022\020.mathtest.RecBro\032\022.mathtest."
  "Datablob\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_tes_5farray_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_tes_5farray_2eproto = {
    false, false, 578, descriptor_table_protodef_tes_5farray_2eproto,
    "tes_array.proto",
    &descriptor_table_tes_5farray_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_tes_5farray_2eproto::offsets,
    file_level_metadata_tes_5farray_2eproto, file_level_enum_descriptors_tes_5farray_2eproto,
    file_level_service_descriptors_tes_5farray_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_tes_5farray_2eproto_getter() {
  return &descriptor_table_tes_5farray_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_tes_5farray_2eproto(&descriptor_table_tes_5farray_2eproto);
namespace mathtest {

// ===================================================================

class MathRequest::_Internal {
 public:
};

MathRequest::MathRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mathtest.MathRequest)
}
MathRequest::MathRequest(const MathRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MathRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_){}
    , decltype(_impl_.b_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.a_, &from._impl_.a_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.b_) -
    reinterpret_cast<char*>(&_impl_.a_)) + sizeof(_impl_.b_));
  // @@protoc_insertion_point(copy_constructor:mathtest.MathRequest)
}

inline void MathRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_){0}
    , decltype(_impl_.b_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MathRequest::~MathRequest() {
  // @@protoc_insertion_point(destructor:mathtest.MathRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MathRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MathRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MathRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mathtest.MathRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.a_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.b_) -
      reinterpret_cast<char*>(&_impl_.a_)) + sizeof(_impl_.b_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MathRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 a = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.a_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 b = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.b_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MathRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mathtest.MathRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 a = 1;
  if (this->_internal_a() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_a(), target);
  }

  // int32 b = 2;
  if (this->_internal_b() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_b(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mathtest.MathRequest)
  return target;
}

size_t MathRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mathtest.MathRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 a = 1;
  if (this->_internal_a() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_a());
  }

  // int32 b = 2;
  if (this->_internal_b() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_b());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MathRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MathRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MathRequest::GetClassData() const { return &_class_data_; }


void MathRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MathRequest*>(&to_msg);
  auto& from = static_cast<const MathRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mathtest.MathRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_a() != 0) {
    _this->_internal_set_a(from._internal_a());
  }
  if (from._internal_b() != 0) {
    _this->_internal_set_b(from._internal_b());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MathRequest::CopyFrom(const MathRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mathtest.MathRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MathRequest::IsInitialized() const {
  return true;
}

void MathRequest::InternalSwap(MathRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MathRequest, _impl_.b_)
      + sizeof(MathRequest::_impl_.b_)
      - PROTOBUF_FIELD_OFFSET(MathRequest, _impl_.a_)>(
          reinterpret_cast<char*>(&_impl_.a_),
          reinterpret_cast<char*>(&other->_impl_.a_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MathRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tes_5farray_2eproto_getter, &descriptor_table_tes_5farray_2eproto_once,
      file_level_metadata_tes_5farray_2eproto[0]);
}

// ===================================================================

class MathReply::_Internal {
 public:
};

MathReply::MathReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mathtest.MathReply)
}
MathReply::MathReply(const MathReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MathReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.result_ = from._impl_.result_;
  // @@protoc_insertion_point(copy_constructor:mathtest.MathReply)
}

inline void MathReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MathReply::~MathReply() {
  // @@protoc_insertion_point(destructor:mathtest.MathReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MathReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MathReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MathReply::Clear() {
// @@protoc_insertion_point(message_clear_start:mathtest.MathReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MathReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MathReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mathtest.MathReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->_internal_result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mathtest.MathReply)
  return target;
}

size_t MathReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mathtest.MathReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->_internal_result() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MathReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MathReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MathReply::GetClassData() const { return &_class_data_; }


void MathReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MathReply*>(&to_msg);
  auto& from = static_cast<const MathReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mathtest.MathReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_internal_set_result(from._internal_result());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MathReply::CopyFrom(const MathReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mathtest.MathReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MathReply::IsInitialized() const {
  return true;
}

void MathReply::InternalSwap(MathReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MathReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tes_5farray_2eproto_getter, &descriptor_table_tes_5farray_2eproto_once,
      file_level_metadata_tes_5farray_2eproto[1]);
}

// ===================================================================

class Mathhasil::_Internal {
 public:
};

Mathhasil::Mathhasil(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mathtest.Mathhasil)
}
Mathhasil::Mathhasil(const Mathhasil& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Mathhasil* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_float_){from._impl_.result_float_}
    , decltype(_impl_.header_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.header_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.header_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_header().empty()) {
    _this->_impl_.header_.Set(from._internal_header(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:mathtest.Mathhasil)
}

inline void Mathhasil::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_float_){arena}
    , decltype(_impl_.header_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.header_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.header_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Mathhasil::~Mathhasil() {
  // @@protoc_insertion_point(destructor:mathtest.Mathhasil)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Mathhasil::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.result_float_.~RepeatedField();
  _impl_.header_.Destroy();
}

void Mathhasil::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Mathhasil::Clear() {
// @@protoc_insertion_point(message_clear_start:mathtest.Mathhasil)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_float_.Clear();
  _impl_.header_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Mathhasil::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_header();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mathtest.Mathhasil.header"));
        } else
          goto handle_unusual;
        continue;
      // repeated float result_float = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_result_float(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 21) {
          _internal_add_result_float(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Mathhasil::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mathtest.Mathhasil)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string header = 1;
  if (!this->_internal_header().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_header().data(), static_cast<int>(this->_internal_header().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mathtest.Mathhasil.header");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_header(), target);
  }

  // repeated float result_float = 2;
  if (this->_internal_result_float_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_result_float(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mathtest.Mathhasil)
  return target;
}

size_t Mathhasil::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mathtest.Mathhasil)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float result_float = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_result_float_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string header = 1;
  if (!this->_internal_header().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_header());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Mathhasil::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Mathhasil::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Mathhasil::GetClassData() const { return &_class_data_; }


void Mathhasil::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Mathhasil*>(&to_msg);
  auto& from = static_cast<const Mathhasil&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mathtest.Mathhasil)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.result_float_.MergeFrom(from._impl_.result_float_);
  if (!from._internal_header().empty()) {
    _this->_internal_set_header(from._internal_header());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Mathhasil::CopyFrom(const Mathhasil& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mathtest.Mathhasil)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Mathhasil::IsInitialized() const {
  return true;
}

void Mathhasil::InternalSwap(Mathhasil* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.result_float_.InternalSwap(&other->_impl_.result_float_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.header_, lhs_arena,
      &other->_impl_.header_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Mathhasil::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tes_5farray_2eproto_getter, &descriptor_table_tes_5farray_2eproto_once,
      file_level_metadata_tes_5farray_2eproto[2]);
}

// ===================================================================

class RecBro::_Internal {
 public:
};

RecBro::RecBro(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mathtest.RecBro)
}
RecBro::RecBro(const RecBro& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RecBro* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){}
    , decltype(_impl_.totalpaket_){}
    , decltype(_impl_.paket_ke_){}
    , decltype(_impl_.mintatipe_){}
    , decltype(_impl_.mintaparam_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.header_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.header_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_header().empty()) {
    _this->_impl_.header_.Set(from._internal_header(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.totalpaket_, &from._impl_.totalpaket_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.mintaparam_) -
    reinterpret_cast<char*>(&_impl_.totalpaket_)) + sizeof(_impl_.mintaparam_));
  // @@protoc_insertion_point(copy_constructor:mathtest.RecBro)
}

inline void RecBro::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){}
    , decltype(_impl_.totalpaket_){0}
    , decltype(_impl_.paket_ke_){0}
    , decltype(_impl_.mintatipe_){0}
    , decltype(_impl_.mintaparam_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.header_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.header_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RecBro::~RecBro() {
  // @@protoc_insertion_point(destructor:mathtest.RecBro)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RecBro::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.header_.Destroy();
}

void RecBro::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RecBro::Clear() {
// @@protoc_insertion_point(message_clear_start:mathtest.RecBro)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.header_.ClearToEmpty();
  ::memset(&_impl_.totalpaket_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.mintaparam_) -
      reinterpret_cast<char*>(&_impl_.totalpaket_)) + sizeof(_impl_.mintaparam_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RecBro::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_header();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mathtest.RecBro.header"));
        } else
          goto handle_unusual;
        continue;
      // int32 totalpaket = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.totalpaket_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 paket_ke = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.paket_ke_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 MintaTipe = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.mintatipe_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 MintaParam = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.mintaparam_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RecBro::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mathtest.RecBro)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string header = 1;
  if (!this->_internal_header().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_header().data(), static_cast<int>(this->_internal_header().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mathtest.RecBro.header");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_header(), target);
  }

  // int32 totalpaket = 2;
  if (this->_internal_totalpaket() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_totalpaket(), target);
  }

  // int32 paket_ke = 3;
  if (this->_internal_paket_ke() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_paket_ke(), target);
  }

  // int32 MintaTipe = 4;
  if (this->_internal_mintatipe() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_mintatipe(), target);
  }

  // int32 MintaParam = 5;
  if (this->_internal_mintaparam() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_mintaparam(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mathtest.RecBro)
  return target;
}

size_t RecBro::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mathtest.RecBro)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string header = 1;
  if (!this->_internal_header().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_header());
  }

  // int32 totalpaket = 2;
  if (this->_internal_totalpaket() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_totalpaket());
  }

  // int32 paket_ke = 3;
  if (this->_internal_paket_ke() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_paket_ke());
  }

  // int32 MintaTipe = 4;
  if (this->_internal_mintatipe() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_mintatipe());
  }

  // int32 MintaParam = 5;
  if (this->_internal_mintaparam() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_mintaparam());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RecBro::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RecBro::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RecBro::GetClassData() const { return &_class_data_; }


void RecBro::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RecBro*>(&to_msg);
  auto& from = static_cast<const RecBro&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mathtest.RecBro)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_header().empty()) {
    _this->_internal_set_header(from._internal_header());
  }
  if (from._internal_totalpaket() != 0) {
    _this->_internal_set_totalpaket(from._internal_totalpaket());
  }
  if (from._internal_paket_ke() != 0) {
    _this->_internal_set_paket_ke(from._internal_paket_ke());
  }
  if (from._internal_mintatipe() != 0) {
    _this->_internal_set_mintatipe(from._internal_mintatipe());
  }
  if (from._internal_mintaparam() != 0) {
    _this->_internal_set_mintaparam(from._internal_mintaparam());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RecBro::CopyFrom(const RecBro& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mathtest.RecBro)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RecBro::IsInitialized() const {
  return true;
}

void RecBro::InternalSwap(RecBro* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.header_, lhs_arena,
      &other->_impl_.header_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RecBro, _impl_.mintaparam_)
      + sizeof(RecBro::_impl_.mintaparam_)
      - PROTOBUF_FIELD_OFFSET(RecBro, _impl_.totalpaket_)>(
          reinterpret_cast<char*>(&_impl_.totalpaket_),
          reinterpret_cast<char*>(&other->_impl_.totalpaket_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RecBro::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tes_5farray_2eproto_getter, &descriptor_table_tes_5farray_2eproto_once,
      file_level_metadata_tes_5farray_2eproto[3]);
}

// ===================================================================

class Datablob::_Internal {
 public:
};

Datablob::Datablob(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mathtest.Datablob)
}
Datablob::Datablob(const Datablob& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Datablob* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){}
    , decltype(_impl_.dataku_){}
    , decltype(_impl_.totalpaket_){}
    , decltype(_impl_.paket_ke_){}
    , decltype(_impl_.tipe_data_){}
    , decltype(_impl_.param_){}
    , decltype(_impl_.timeepoch_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.header_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.header_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_header().empty()) {
    _this->_impl_.header_.Set(from._internal_header(), 
      _this->GetArenaForAllocation());
  }
  _impl_.dataku_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dataku_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_dataku().empty()) {
    _this->_impl_.dataku_.Set(from._internal_dataku(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.totalpaket_, &from._impl_.totalpaket_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timeepoch_) -
    reinterpret_cast<char*>(&_impl_.totalpaket_)) + sizeof(_impl_.timeepoch_));
  // @@protoc_insertion_point(copy_constructor:mathtest.Datablob)
}

inline void Datablob::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){}
    , decltype(_impl_.dataku_){}
    , decltype(_impl_.totalpaket_){0}
    , decltype(_impl_.paket_ke_){0}
    , decltype(_impl_.tipe_data_){0}
    , decltype(_impl_.param_){0}
    , decltype(_impl_.timeepoch_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.header_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.header_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.dataku_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dataku_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Datablob::~Datablob() {
  // @@protoc_insertion_point(destructor:mathtest.Datablob)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Datablob::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.header_.Destroy();
  _impl_.dataku_.Destroy();
}

void Datablob::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Datablob::Clear() {
// @@protoc_insertion_point(message_clear_start:mathtest.Datablob)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.header_.ClearToEmpty();
  _impl_.dataku_.ClearToEmpty();
  ::memset(&_impl_.totalpaket_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timeepoch_) -
      reinterpret_cast<char*>(&_impl_.totalpaket_)) + sizeof(_impl_.timeepoch_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Datablob::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_header();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mathtest.Datablob.header"));
        } else
          goto handle_unusual;
        continue;
      // int32 totalpaket = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.totalpaket_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 paket_ke = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.paket_ke_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tipe_data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.tipe_data_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 param = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.param_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 timeEpoch = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.timeepoch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes dataku = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_dataku();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Datablob::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mathtest.Datablob)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string header = 1;
  if (!this->_internal_header().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_header().data(), static_cast<int>(this->_internal_header().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mathtest.Datablob.header");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_header(), target);
  }

  // int32 totalpaket = 2;
  if (this->_internal_totalpaket() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_totalpaket(), target);
  }

  // int32 paket_ke = 3;
  if (this->_internal_paket_ke() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_paket_ke(), target);
  }

  // int32 tipe_data = 4;
  if (this->_internal_tipe_data() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_tipe_data(), target);
  }

  // int32 param = 5;
  if (this->_internal_param() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_param(), target);
  }

  // int32 timeEpoch = 6;
  if (this->_internal_timeepoch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_timeepoch(), target);
  }

  // bytes dataku = 7;
  if (!this->_internal_dataku().empty()) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_dataku(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mathtest.Datablob)
  return target;
}

size_t Datablob::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mathtest.Datablob)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string header = 1;
  if (!this->_internal_header().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_header());
  }

  // bytes dataku = 7;
  if (!this->_internal_dataku().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_dataku());
  }

  // int32 totalpaket = 2;
  if (this->_internal_totalpaket() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_totalpaket());
  }

  // int32 paket_ke = 3;
  if (this->_internal_paket_ke() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_paket_ke());
  }

  // int32 tipe_data = 4;
  if (this->_internal_tipe_data() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tipe_data());
  }

  // int32 param = 5;
  if (this->_internal_param() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_param());
  }

  // int32 timeEpoch = 6;
  if (this->_internal_timeepoch() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_timeepoch());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Datablob::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Datablob::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Datablob::GetClassData() const { return &_class_data_; }


void Datablob::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Datablob*>(&to_msg);
  auto& from = static_cast<const Datablob&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mathtest.Datablob)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_header().empty()) {
    _this->_internal_set_header(from._internal_header());
  }
  if (!from._internal_dataku().empty()) {
    _this->_internal_set_dataku(from._internal_dataku());
  }
  if (from._internal_totalpaket() != 0) {
    _this->_internal_set_totalpaket(from._internal_totalpaket());
  }
  if (from._internal_paket_ke() != 0) {
    _this->_internal_set_paket_ke(from._internal_paket_ke());
  }
  if (from._internal_tipe_data() != 0) {
    _this->_internal_set_tipe_data(from._internal_tipe_data());
  }
  if (from._internal_param() != 0) {
    _this->_internal_set_param(from._internal_param());
  }
  if (from._internal_timeepoch() != 0) {
    _this->_internal_set_timeepoch(from._internal_timeepoch());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Datablob::CopyFrom(const Datablob& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mathtest.Datablob)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Datablob::IsInitialized() const {
  return true;
}

void Datablob::InternalSwap(Datablob* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.header_, lhs_arena,
      &other->_impl_.header_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.dataku_, lhs_arena,
      &other->_impl_.dataku_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Datablob, _impl_.timeepoch_)
      + sizeof(Datablob::_impl_.timeepoch_)
      - PROTOBUF_FIELD_OFFSET(Datablob, _impl_.totalpaket_)>(
          reinterpret_cast<char*>(&_impl_.totalpaket_),
          reinterpret_cast<char*>(&other->_impl_.totalpaket_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Datablob::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tes_5farray_2eproto_getter, &descriptor_table_tes_5farray_2eproto_once,
      file_level_metadata_tes_5farray_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mathtest
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mathtest::MathRequest*
Arena::CreateMaybeMessage< ::mathtest::MathRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mathtest::MathRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mathtest::MathReply*
Arena::CreateMaybeMessage< ::mathtest::MathReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mathtest::MathReply >(arena);
}
template<> PROTOBUF_NOINLINE ::mathtest::Mathhasil*
Arena::CreateMaybeMessage< ::mathtest::Mathhasil >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mathtest::Mathhasil >(arena);
}
template<> PROTOBUF_NOINLINE ::mathtest::RecBro*
Arena::CreateMaybeMessage< ::mathtest::RecBro >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mathtest::RecBro >(arena);
}
template<> PROTOBUF_NOINLINE ::mathtest::Datablob*
Arena::CreateMaybeMessage< ::mathtest::Datablob >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mathtest::Datablob >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
